version: '2.1'

services:

  gateway:
    build: ../../cloud/eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/gateway-docker-compose.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
    volumes:
      - $PWD/keystore:/keystore
    mem_limit: 350m
    ports:
      - "443:8080"

  eureka:
    build: ../../cloud/eureka
    mem_limit: 350m
    ports:
      - "8761:8761"

  product:
    build: ../../services/product
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongoDB:
        condition: service_healthy

  recommend:
    build: ../../services/recommend
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongoDB:
        condition: service_healthy

  review:
    build: ../../services/review
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysqldb:
        condition: service_healthy

  composite:
    build: ../../services/composite
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongoDB:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats() ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  mysqldb:
    image: mysql:5.7
    mem_limit: 35m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=user01
    healthcheck:
      test: ["CMD", "myslqadmin", "ping", "-uuser01", "-puser01", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
