server:
  port: 80  # Spring boot Server port
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: false
      path: /test_db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: info
    com.example: debug