spring:
  h2:
    console:
      enabled: true
      path: /h2_amdin
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./dev_db;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false