server:
  port: 8080
app:
  product:
    host: product
    prot: 8080
  recommend:
    host: recommend
    prot: 8080
  review:
    host: review
    prot: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/