server:
  port: 7001
  error:
    include-message: always
spring:
  application:
    name: product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initalalInstanceInfoReplicationIntervalSeconds : 5
    registryFetchIntervalSeconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
logging:
  level:
    root: INFO
    com.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG