server:
  port: 8000

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: my_client
  credentials:
    secret: f65f2b24-83dc-4f75-8e18-0b45f51b7564
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    com.cloud.sb106: DEBUG