server:
  port: 8040
spring:
  application:
    name: biz
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/auth/realms/my_realm
logging:
  level:
    com.cloud: DEBUG
