server:
  port: 7003
  error:
    include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user01
    password: user01
    hikari:
      initializationFailTimeout: 60000
logging:
  level:
    root: INFO
    com.cloud.review: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE